version: "3.1"

services:
  exchange-rates:
    build:
      context: ./../
      dockerfile: Dockerfile
    restart: always
    container_name: exchangeRates-service
    ports:
      - 8180:8080
    working_dir: /opt/app
    depends_on:
      - mongo


  mongo:
    image: mongo
    container_name: service-db
    ports:  # for debug purpose only
      - 27017:27017
    volumes:
      - ./../db-data/data:/data/db
      - ./../db-data/bkp:/data/bkp
    restart: always
